manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: nmunnich
      url-base: https://github.com/nmunnich
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: nmunnich
      revision: behavior-event
      import: app/west.yml
  self:
    path: config
